[project]
name = "wasplash"
description = "wasplash to guapo"
authors = []
telemetry = true
cache_dir = "./.cache"

# [contracts.SP1AJVMEGSMD6QCSZ1669Z5G90GEHVK2MEM7J0AHH.wasplash]
# path = "contracts/wasplash.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
